app_name: tg-collector
env: dev

logger:
  level: info
  json: false

runtime:
  shutdown_timeout: 15s

storage:
  driver: postgres
  postgres:
    dsn: ""
    max_open_conns: 4
    max_idle_conns: 2
    conn_max_lifetime: 30m
    conn_max_idle_time: 5m

mtproto:
  # Забираем с my.telegram.org.
  api_id: 12345678

  # Забираем с my.telegram.org.
  api_hash: "..."

  # При первом успешном bootstrap запуске все будет
  session: "runtime/tgcollector/session.json"
  phone: "+7..."

  # 2FA
  password: ""

  # Первый запуск на новой машине -> true
  # для обычной работы (когда уже есть session.json)  -> false
  allow_interactive_auth: false

  device:
    model: "PC"
    system: "Windows 10"
    app_version: "1.0.0"
    lang_code: "ru"
    system_lang: "ru"

  rate_limit:
    # Задержка между MTProto запросами (чтобы не нарваться на бан)
    min_delay: 3s
    concurrency: 1

scrape:
  channels:
    - "@somechannel"
    - "https://t.me/anotherchannel"
  keywords:
    - "test"
    - "leak"

  # Насколько глубоко в прошлое смотреть сообщения при сканировании
  # 168h = 7 дней.
  lookback: 168h

  # Окно хранения hit'ов для дедупликации и последующей очистки
  # 720h = 30 дней.
  dedup_window: 720h

  # Максимальное число сообщений, которое collector просматривает
  # за один проход по одному каналу.
  per_channel_max_scan: 300

  # Минимальная пауза между запросами истории сообщений внутри канала
  min_delay: 2s

  # Пауза между обработкой разных каналов.
  between_channels_delay: 3s

  # Как часто collector запускает очередной полный цикл обхода каналов
  interval: 3m