ALTER TABLE hits
    ADD COLUMN IF NOT EXISTS category      TEXT NULL,
    ADD COLUMN IF NOT EXISTS classified_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS llm_model     TEXT NULL,
    ADD COLUMN IF NOT EXISTS llm_confidence DOUBLE PRECISION NULL,
    ADD COLUMN IF NOT EXISTS llm_reason    TEXT NULL;